# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Edison's Blog
tagline:          'Make everything better'
description:      'Thinking, writing and sharing'

author:
  name:           'Edison'
  url:            https://zhangn661.com/about

paginate:         5

# Custom vars
version:          2.1.0
plugins_dir:
        - jekyll-paginate
        - jekyll-gist

# gems: [jekyll-paginate,jekyll-gist,jekyll-twitter-plugin]

# plugins: [jekyll-paginate,jekyll-gist,jekyll-twitter-plugin]

github:
  repo:           https://github.com/Edison-A-N"


google_analytics: UA-188648772-3
