# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Edison's Blog
tagline:          'A Jekyll theme'
description:      'Thinking, writing and sharing'
url:              https://zhangn661.com/

author:
  name:           'Edison'
  url:            zhangn661@gmail.com

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
